source "https://rubygems.org"

# Point to local Oroshi engine gem
gem "oroshi", path: ".."

# Rails and Ruby version
ruby file: "../.ruby-version"

# PostgreSQL database
gem "pg", "~> 1.1"

# Puma web server
gem "puma", ">= 5.0"

# The rest will come from Oroshi gem dependencies
